import frappe
import json
import sys

frappe.init(site="branch01.local")
frappe.connect()

payload_json = """{
 "doc": {
  "__onload": {
   "make_payment_via_journal_entry": 0
  },
  "account_for_change_amount": "Cash - Jkt",
  "additional_discount_percentage": 0.0,
  "address_display": null,
  "advances": [],
  "against_income_account": null,
  "allocate_advances_automatically": 0,
  "amended_from": null,
  "amount_eligible_for_commission": 200.0,
  "apply_discount_on": "Grand Total",
  "auto_repeat": null,
  "base_change_amount": 0.0,
  "base_discount_amount": 0.0,
  "base_grand_total": 200.0,
  "base_in_words": "AFN Two Hundred only.",
  "base_net_total": 200.0,
  "base_paid_amount": 200.0,
  "base_rounded_total": 200.0,
  "base_rounding_adjustment": 0.0,
  "base_total": 200.0,
  "base_total_taxes_and_charges": 0.0,
  "base_write_off_amount": 0.0,
  "branch": null,
  "campaign": null,
  "cash_bank_account": null,
  "change_amount": 0.0,
  "commission_rate": 0.0,
  "company": "Jahan kodak testing",
  "company_address": null,
  "company_address_display": null,
  "company_contact_person": null,
  "consolidated_invoice": null,
  "contact_display": null,
  "contact_email": null,
  "contact_mobile": null,
  "contact_person": null,
  "conversion_rate": 1.0,
  "cost_center": null,
  "coupon_code": null,
  "creation": "2026-09-29 09:26:24.619253",
  "currency": "AFN",
  "custom_exchange_id": null,
  "custom_exchange_receipt_data": null,
  "custom_linked_exchange_invoice": null,
  "customer": "Walking Customer",
  "customer_address": null,
  "customer_group": null,
  "customer_name": "Walking Customer",
  "debit_to": "Debtors - Jkt",
  "discount_amount": 0.0,
  "docstatus": 1,
  "doctype": "POS Invoice",
  "due_date": "2026-09-29",
  "from_date": null,
  "grand_total": 200.0,
  "group_same_items": 0,
  "idx": 0,
  "ignore_pricing_rule": 0,
  "in_words": "AFN Two Hundred only.",
  "inter_company_invoice_reference": null,
  "is_discounted": 0,
  "is_opening": "No",
  "is_pos": 1,
  "is_return": 0,
  "items": [
   {
    "__unsaved": 1,
    "actual_batch_qty": 0.0,
    "actual_qty": 15.0,
    "allow_zero_valuation_rate": 0,
    "amount": 200.0,
    "asset": null,
    "barcode": null,
    "base_amount": 200.0,
    "base_net_amount": 200.0,
    "base_net_rate": 200.0,
    "base_price_list_rate": 200.0,
    "base_rate": 200.0,
    "base_rate_with_margin": 0.0,
    "batch_no": "",
    "branch": null,
    "brand": null,
    "conversion_factor": 1.0,
    "cost_center": "Main - Jkt",
    "creation": "2026-09-29 09:26:24.619253",
    "customer_item_code": null,
    "deferred_revenue_account": null,
    "delivered_by_supplier": 0,
    "delivered_qty": 0.0,
    "delivery_note": null,
    "description": "cloths-0001",
    "discount_amount": 0.0,
    "discount_percentage": 0.0,
    "distributed_discount_amount": 0.0,
    "dn_detail": null,
    "docstatus": 1,
    "doctype": "POS Invoice Item",
    "enable_deferred_revenue": 0,
    "expense_account": "Cost of Goods Sold - Jkt",
    "finance_book": null,
    "grant_commission": 1,
    "has_item_scanned": 0,
    "idx": 1,
    "image": "",
    "income_account": "Sales - Jkt",
    "is_fixed_asset": 0,
    "is_free_item": 0,
    "item_code": "1001",
    "item_group": "Jahan kodak items",
    "item_name": "cloths-0001",
    "item_tax_rate": "{}",
    "item_tax_template": null,
    "margin_rate_or_amount": 0.0,
    "margin_type": "",
    "modified": "2026-09-29 09:26:26.360590",
    "modified_by": "Administrator",
    "name": "cdo9pq9av1",
    "net_amount": 200.0,
    "net_rate": 200.0,
    "owner": "Administrator",
    "page_break": 0,
    "parent": "branch01.local-ACC-PSINV-2026-04311",
    "parentfield": "items",
    "parenttype": "POS Invoice",
    "pos_invoice_item": null,
    "price_list_rate": 200.0,
    "pricing_rules": "",
    "project": null,
    "qty": 1.0,
    "quality_inspection": null,
    "rate": 200.0,
    "rate_with_margin": 0.0,
    "sales_order": null,
    "serial_and_batch_bundle": null,
    "serial_no": null,
    "service_end_date": null,
    "service_start_date": null,
    "service_stop_date": null,
    "so_detail": null,
    "stock_qty": 1.0,
    "stock_uom": "Nos",
    "target_warehouse": null,
    "total_weight": 0.0,
    "uom": "Nos",
    "use_serial_batch_fields": 1,
    "warehouse": "Stores - Jkt",
    "weight_per_unit": 0.0,
    "weight_uom": null
   }
  ],
  "language": "en",
  "last_scanned_warehouse": null,
  "letter_head": "Ahangarzada",
  "loyalty_amount": 0.0,
  "loyalty_points": 0,
  "loyalty_program": null,
  "loyalty_redemption_account": null,
  "loyalty_redemption_cost_center": null,
  "modified": "2026-09-29 09:26:26.360590",
  "modified_by": "Administrator",
  "name": "branch01.local-ACC-PSINV-TEST-001",
  "naming_series": "ACC-PSINV-.YYYY.-",
  "net_total": 200.0,
  "other_charges_calculation": null,
  "outstanding_amount": 0.0,
  "owner": "Administrator",
  "packed_items": [],
  "paid_amount": 200.0,
  "party_account_currency": "AFN",
  "payment_schedule": [],
  "payment_terms_template": null,
  "payments": [
   {
    "__unsaved": 1,
    "account": "10100 - Daily Sales - Jkt",
    "amount": 0.0,
    "base_amount": 0.0,
    "clearance_date": null,
    "creation": "2026-09-29 09:26:24.619253",
    "default": 0,
    "docstatus": 1,
    "doctype": "Sales Invoice Payment",
    "idx": 1,
    "mode_of_payment": "Cheque",
    "modified": "2026-09-29 09:26:26.360590",
    "modified_by": "Administrator",
    "name": "cdop2qpm9t",
    "owner": "Administrator",
    "parent": "branch01.local-ACC-PSINV-2026-04311",
    "parentfield": "payments",
    "parenttype": "POS Invoice",
    "reference_no": null,
    "type": "Bank"
   },
   {
    "__unsaved": 1,
    "account": "10100 - Daily Sales - Jkt",
    "amount": 200.0,
    "base_amount": 200.0,
    "clearance_date": null,
    "creation": "2026-09-29 09:26:24.619253",
    "default": 1,
    "docstatus": 1,
    "doctype": "Sales Invoice Payment",
    "idx": 2,
    "mode_of_payment": "Cash",
    "modified": "2026-09-29 09:26:26.360590",
    "modified_by": "Administrator",
    "name": "cdoab7kc1q",
    "owner": "Administrator",
    "parent": "branch01.local-ACC-PSINV-2026-04311",
    "parentfield": "payments",
    "parenttype": "POS Invoice",
    "reference_no": null,
    "type": "Cash"
   }
  ],
  "plc_conversion_rate": 1.0,
  "po_date": null,
  "po_no": null,
  "pos_profile": "test sync pos profile",
  "posting_date": "2026-09-29",
  "posting_time": "09:26:26.909563",
  "price_list_currency": "AFN",
  "pricing_rules": [],
  "project": null,
  "redeem_loyalty_points": 0,
  "remarks": "No Remarks",
  "return_against": null,
  "rounded_total": 200.0,
  "rounding_adjustment": 0.0,
  "sales_partner": null,
  "sales_team": [],
  "scan_barcode": null,
  "select_print_heading": null,
  "selling_price_list": "\u0644\u06cc\u0633\u062a \u0642\u06cc\u0645\u062a \u0641\u0631\u0648\u0634",
  "set_posting_time": 0,
  "set_warehouse": "Stores - Jkt",
  "shipping_address": null,
  "shipping_address_name": null,
  "shipping_rule": null,
  "source": null,
  "status": "Paid",
  "tax_category": "",
  "tax_id": null,
  "taxes": [],
  "taxes_and_charges": "",
  "tc_name": null,
  "terms": null,
  "territory": null,
  "timesheets": [],
  "title": "Walking Customer",
  "to_date": null,
  "total": 200.0,
  "total_advance": 0.0,
  "total_billing_amount": 0.0,
  "total_commission": 0.0,
  "total_net_weight": 0.0,
  "total_qty": 1.0,
  "total_taxes_and_charges": 0.0,
  "update_billed_amount_in_delivery_note": 1,
  "update_billed_amount_in_sales_order": 0,
  "write_off_account": "Write Off - Jkt",
  "write_off_amount": 0.0,
  "write_off_cost_center": "Main - Jkt",
  "write_off_outstanding_amount_automatically": 0
 }
}"""

payload = json.loads(payload_json)

from jk_sync.handlers.pos_invoice import handle_pos_invoice

try:
    frappe.db.savepoint("test")
    handle_pos_invoice(payload)
except Exception as e:
    import traceback
    print("Caught Exception:", e)
    traceback.print_exc()
finally:
    frappe.db.rollback(save_point="test")
    

def run():
	pass
