import frappe

def log_stock_ledger_entry(doc, method):
    """
    Hook for Stock Ledger Entry (after_insert).
    Runs on the Cloud Server to log stock changes for branch synchronization.
    """
    # 1. Determine if this SLE is for a Branch Warehouse
    # Assuming Branch Warehouses can be identified by the branch_id in Branch Sync Config.
    # Alternatively, we could map Warehouse -> Branch ID.
    # For now, let's assume we can lookup the Branch ID for this warehouse.
    # (A custom field 'branch_id' on Warehouse would be best).
    # Since we don't have that yet, let's just assume we check all active configs.
    
    # We only log SLEs that are NOT generated by the jk_sync process itself.
    # We can detect this by checking frappe.flags.is_syncing.
    if getattr(frappe.flags, "is_syncing", False):
        return
        
    branch_id = getattr(doc, "branch_id", None)
    if not branch_id:
        # Try to infer from warehouse
        # If the warehouse name contains the branch ID, or we add a custom field.
        # Let's add a custom field lookup (we will create it next)
        branch_id = frappe.db.get_value("Warehouse", doc.warehouse, "branch_id")
        
    if not branch_id:
        return
        
    # Ignore SLEs from POS Closing (as they are inherently local)
    if doc.voucher_type == "POS Closing Entry":
        return
        
    # Log the Delta
    log = frappe.get_doc({
        "doctype": "Cloud Stock Sync Log",
        "branch_id": branch_id,
        "item_code": doc.item_code,
        "warehouse": doc.warehouse,
        "qty_change": doc.actual_qty,
        "reference_doctype": doc.voucher_type,
        "reference_name": doc.voucher_no
    })
    log.insert(ignore_permissions=True)
